<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_SD_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d1a9ff22-69df-45ac-b353-974758039ee1</testSuiteGuid>
   <testCaseLink>
      <guid>8d8020d4-3615-44f5-99de-6932cdf6e3db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SatrioAdiPrawiro-Quiz6/SAP6-02</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>23e68db5-da5a-484f-99ac-780464dd0da0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Raw Data/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>23e68db5-da5a-484f-99ac-780464dd0da0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>3e52a56e-e422-47bd-8223-9f76918f35ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>23e68db5-da5a-484f-99ac-780464dd0da0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>8680fd18-95b9-4ce9-acb3-0a3284ede54f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
