<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d1a9ff22-69df-45ac-b353-974758039ee1</testSuiteGuid>
   <testCaseLink>
      <guid>5ac6461e-d8be-4787-9e53-b53b8e16dc2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>19fe967b-1564-4705-aff2-848d45b84489</id>
         <masked>false</masked>
         <name>Username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Common Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>98f65134-8ce1-4e27-bb64-253baae81430</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Raw Data/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>98f65134-8ce1-4e27-bb64-253baae81430</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>19fe967b-1564-4705-aff2-848d45b84489</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>98f65134-8ce1-4e27-bb64-253baae81430</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>75fa3d79-7e92-4d55-b359-f7c9493ea288</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
